Created Faves container, Favourite component, and a favourite list it…
redacademy/coyote-winter-2018 pull request #87
Opened 2018-03-19 18:44 UTC by colinmj

…em. Pulling favourites from the database and displaying on the favourite screen

Created faves container

Logging listings from firestore

Started faves reducer

Getting faves in the faves container

Adding faves to redux store

Created Faves page

2018-03-19 18:46 UTC, colinmj commented
There are a couple small things we still need to add to the faves page, once Icons are linked I will add a heart, and once we have the navigation pulled I will use firebaseAuth to get the current user. For now I have a hard coded user Id

2018-03-19 20:56 UTC, siddharthparmar7 requested changes
Please make the requested changes so I can approve it. Thank you!

2018-03-19 20:56 UTC, siddharthparmar7 commented on js/components/FavouriteItem/FavouriteItem.js
> +          {' '}
Please remove {'  '} from your code.

2018-03-19 20:56 UTC, siddharthparmar7 commented on js/components/FavouriteItem/FavouriteItem.js
> +          Last Updated:{' '}
Please remove {' '} from your code.

2018-03-19 20:56 UTC, siddharthparmar7 commented on js/index.js
> +        {/* <LocationSearchContainer /> */}
Please remove this commented code.

2018-03-19 20:56 UTC, siddharthparmar7 commented on js/index.js
> +import LocationSearchContainer from './screens/LocationSearch/';
Please remove this import if you are not using this component.

2018-03-19 20:56 UTC, siddharthparmar7 commented on js/screens/Favourite/FavouriteContainer.js
> +    firestoreDb
your firebase implementation should be inside a helper file.

2018-03-19 20:56 UTC, siddharthparmar7 commented on js/screens/Favourite/FavouriteContainer.js
> +class FavouriteScreen extends Component {
Your file and your class name should be same.

2018-03-19 20:59 UTC, siddharthparmar7 reviewed
Please add dependencies and assign yourself to this issues.

2018-03-20 21:53 UTC, siddharthparmar7 approved these changes
Thank you! Colin! Please make sure to squash your commits next time.

Thank you!

2018-03-20 21:53 UTC, merged